//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersDetail
    {
        public int OrdersDetailID { get; set; }
        public int OrdersDetailProductID { get; set; }
        public int OrdersDetailOrderID { get; set; }
        public int OrdersDetailQuanlity { get; set; }

        public int TotalMonneyDetail { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
